apiVersion: v1
kind: Service
metadata:
  name: k8s-user-service
  namespace: movie-web
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
