apiVersion: v1
kind: Service
metadata:
  name: k8s-movie-service
  namespace: movie-web
spec:
  type: ClusterIP
  selector:
    app: movie-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
