apiVersion: v1
kind: Secret
metadata:
  name: movie-service-secret
  namespace: movie-web
stringData:
  MONGO_URL: "mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/netflix?retryWrites=true&w=majority&appName=BackendDB"
  SECRET_KEY: "happynewyear"