apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service
  namespace: movie-web
  labels:
    app: bill-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-service
  template:
    metadata:
      labels:
        app: bill-service
    spec:
      containers:
        - name: bill-service
          image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-bill-service:v5_4f2808fd
          ports:
            - containerPort: 3003
              protocol: TCP  
          resources:
            requests:
              memory: "256Mi"
          env:
            - name: USER_SERVER_HOST
              value: k8s-user-service
            - name: USER_SERVER_PORT
              value: "3001"
          envFrom:
            - secretRef:
                name: bill-service-secret
      imagePullSecrets:
        - name: auth-registry