apiVersion: v1
kind: Service
metadata:
  name: k8s-bill-service
  namespace: movie-web
spec:
  type: ClusterIP
  selector:
    app: bill-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
