apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscale  
  namespace: movie-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-web-frontend  
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
