apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-web-frontend 
  namespace: movie-web
  labels:
    app: movie-web-frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-web-frontend 
  template:
    metadata:
      labels:
        app: movie-web-frontend 
    spec:
      containers:
        - name: movie-web-frontend 
          image: dev.nhatanhdevops.website/onlineshop/movie-web-frontend-production:v13_cd333805
          ports:
            - containerPort: 80
              protocol: TCP  
          resources:
            requests:
              memory: "256Mi"
          env:
            - name: REACT_APP_GATEWAY_HOST
              value: "k8s-api-gateway"
            - name: REACT_APP_GATEWAY_PORT
              value: "8800"
          envFrom:
            - secretRef:
                name: movie-web-frontend-secret
      imagePullSecrets:
        - name: auth-registry
