version: '3.8'

services:
  api-gateway:
    image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-api-gateway:v1_58b9dbf3
    container_name: api-gateway
    restart: always
    ports:
      - "8800:8800"
    environment:
      - SERVER_1_HOST=user-service
      - SERVER_1_PORT=3001
      - SERVER_2_HOST=movie-service
      - SERVER_2_PORT=3002
      - SERVER_3_HOST=bill-service
      - SERVER_3_PORT=3003
    depends_on:
      - user-service
      - movie-service
      - bill-service
    networks:
      - movie-web
  bill-service:
    image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-bill-service:v1_68c44813
    container_name: bill-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/netflix?retryWrites=true&w=majority&appName=BackendDB
      - SECRET_KEY=happynewyear
      - KEY_1=sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn
      - KEY_2=trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
      - APP_ID=2554
      - APP_URL=https://movieclient.netlify.app
      - USER_SERVER_HOST=user-service
      - USER_SERVER_PORT=3001
    networks:
      - movie-web
  movie-service:
    image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-movie-service:v1_942e16fb
    container_name: movie-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/netflix?retryWrites=true&w=majority&appName=BackendDB
      - SECRET_KEY=happynewyear
      - USER_SERVER_HOST=user-service
      - USER_SERVER_PORT=3001
      - ELASTIC_SEARCH_HOST=192.168.80.111
      - ELASTIC_SEARCH_PORT=31111
    networks:
      - movie-web
  user-service:
    image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-user-service:v1_5306b095
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - CLIENT_ID=1052930060682-ggqlj8qjlbs37nan4p0ug1bira27ne8i.apps.googleusercontent.com
      - CLIENT_SECRET=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
      - REDIRECT_URI=https://developers.google.com/oauthplayground
      - REFRESH_TOKEN=1//04Ly3viWbJGOECgYIARAAGAQSNwF-L9IrVdtnjpjTHbFSGB7avHeQ-ymgjmQ1OeJve3Fdwuyj6i43fuca4vy7sYCXQ4fe4syCzLI
      - ADMIN_MAIL=alonhuan123@gmail.com
      - MONGO_URL=mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/netflix?retryWrites=true&w=majority&appName=BackendDB
      - SECRET_KEY=happynewyear
      - KAFKA_HOST=192.168.80.230
      - KAFKA_PORT=9094
      - KAFKA_GROUP=movie-web
      - KAFKA_TOPIC=mail-services
      - MOVIE_SERVER_HOST=movie-service
      - MOVIE_SERVER_PORT=3002
    networks:
      - movie-web


networks:
  movie-web:
    driver: bridge
