version: '3.8'

services:
  movie-web-frontend:
    image: dev.nhatanhdevops.website/onlineshop/movie-web-frontend:v1_8f6cae93
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_GENERATE_SOURCEMAP=false
      - REACT_APP_GATEWAY_HOST=192.168.80.240
      - REACT_APP_GATEWAY_PORT=8800
