apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: movie-web
spec: 
  selector:
    app: elasticsearch
  ports: 
  - port: 9200
    name: http
  - port: 9300
    name: transport
  type: ClusterIP